name: prod-angular-nodejs
services:

  angular:
    container_name: prod-angular
    build:
      context: ./frontend
      target: production
    ports:
      - '80:80'

  nodejs:
    container_name: prod-nodejs
    build:
      context: ./backend
      target: production
    ports:
      - 3080:3080
    environment:
      NODE_ENV: production
    volumes:
      - ./src:/usr/src/app/src

#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

