name: test-angular-nodejs
services:
  angular:
    container_name: test-angular
    build:
      context: ./frontend
      target: testing
    ports:
      - '4010:4010'
      - '9876:9876'
    networks:
      - testnet

  nodejs:
    container_name: test-nodejs
    build:
      context: ./backend
      target: testing
    ports:
      - 8080:8080
    environment:
      NODE_ENV: testing
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - testnet
        
  postgresql:
    container_name: test-postgresql
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=prod_angular-nodejs
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5430:5430
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - testnet


volumes:
  db-data:

secrets:
  db-password:
    file: db/pg.test
    
networks:
  testnet:
